spring:
    flyway:
        baseline-on-migrate: true
    datasource:
        url: jdbc:postgresql://localhost:${POSTGRES_PORT}/test
        username: test
        password: test
        driver-class-name: org.postgresql.Driver
server:
    port: 8090

nbp:
    url: http://api.nbp.pl/api/exchangerates/rates/A/USD
