spring:
    flyway:
        baseline-on-migrate: true
    datasource:
        url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/currency_exchange_db}
        username: ${DATABASE_USERNAME:myuser}
        password: ${DATABASE_PASSWORD:mypassword}
        driver-class-name: org.postgresql.Driver

nbp:
    url: http://api.nbp.pl/api/exchangerates/rates/A/USD
